# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Use a smaller Node.js image for the runtime
FROM node:16-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Copy the .env file (should be mounted as a volume for secrets)
# COPY .env .env

# Expose a port if needed (add this line if you have a specific port to expose)
# EXPOSE 3000

# Set the command to run the server
ENTRYPOINT ["node", "build/index.js"]